//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCUTEAW_App.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCUTEAW_App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/LinZong/SCUTEAW-App-Docs/blob/master/cookie-mode-login/cookie-mode-login.md 的本地化字符串。
        /// </summary>
        public static string CookieModeGuideUrl {
            get {
                return ResourceManager.GetString("CookieModeGuideUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon EnChan {
            get {
                object obj = ResourceManager.GetObject("EnChan", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 JSESSION shouldn&apos;t be empty. 的本地化字符串。
        /// </summary>
        public static string NeedJSESSION {
            get {
                return ResourceManager.GetString("NeedJSESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Student Id shouldn&apos;t be empty. 的本地化字符串。
        /// </summary>
        public static string NeedStudentId {
            get {
                return ResourceManager.GetString("NeedStudentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BIGipServerjwxtnew_BS80 shouldn&apos;t be empty. 的本地化字符串。
        /// </summary>
        public static string NeesJwxtToken {
            get {
                return ResourceManager.GetString("NeesJwxtToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy string must be url format. 的本地化字符串。
        /// </summary>
        public static string ProxyMustBeUrl {
            get {
                return ResourceManager.GetString("ProxyMustBeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Student Id should be number. 的本地化字符串。
        /// </summary>
        public static string StudentIdNeedNumber {
            get {
                return ResourceManager.GetString("StudentIdNeedNumber", resourceCulture);
            }
        }
    }
}
